name: release

on:
  push:
    tags:
      - "v*"

jobs:
  publish-github:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Publish package to GitHub Packages
        run: |
          mvn -s ${{ github.workspace }}/.github/workflows/settings.xml --batch-mode deploy
          rm -rf */target/original-*.jar
        env:
          USERNAME: ${{ secrets.USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: "*/target/*.jar"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  publish-gar:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Authenticate to Google Cloud
        id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/216572124863/locations/global/workloadIdentityPools/github-actions/providers/github-actions
          service_account: kryptonite-gha@merpay-dataplatform-jp-prod.iam.gserviceaccount.com
          token_format: 'access_token'
      - name: Publish package to GAR
        run: |
          mvn -s ${{ github.workspace }}/.github/workflows/settings.xml -P gar --batch-mode deploy
        env:
          GAR_ACCESS_TOKEN: ${{ steps.gcp-auth.outputs.access_token }}
